name: docs

on:
  push:
    branches:
      - main
    paths:
      - "svgdatagrabber/**"
      - "docs/source/**"
      - ".github/workflows/pages.yml"
  pull_request:
    branches:
      - main
    paths:
      - "svgdatagrabber/**"
      - "docs/source/**"
      - ".github/workflows/pages.yml"
  workflow_dispatch:

concurrency:
  group: pages-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Installing the library
        run: |
          pip install -e .[docs]
      - name: Build and Commit
        uses: sphinx-notes/pages@v2
        with:
          documentation_path: docs
