name: Pages
on:
  push:
    branches:
    - main
    paths:
    - 'SSI/**'
    - 'docs/source/**'
    - '.github/workflows/pages.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: pages_staging_environment
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Installing the library
      shell: bash -l {0}
      run: |
        pip install -r docs/requirements.txt
        pip install .
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        documentation_path: docs
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
